import numpy
import streamlit as st

st.title("John Doe")
st.subheader("Full Stack Developer")
st.write("---")
st.header("Summary")
st.write("A full stack developer with experience in Python, Flask, React and Vue.js. Passionate about learning new technologies and developing innovative solutions.")
st.write("---")
st.header("Skills")
st.write("- Python")
st.write("- Flask")
st.write("- React")
st.write("- Vue.js")
st.write("- HTML")
st.write("- CSS")
st.write("---")
st.header("Experience")
st.subheader("Full Stack Developer at XYZ Company")
st.write("June 2020 - Present")
st.write("- Developed and maintained a Flask-based web application for tracking inventory")
st.write("- Built and maintained a React-based dashboard for data visualization")
st.write("---")
st.header("Education")
st.subheader("Bachelor's Degree in Computer Science")
st.write("University of ABC")
st.write("2016 - 2020")